This is a simple Spring Boot based app to collect and aggregate custom app metrics and present the aggregations via a RESTful API. 

This app depends on https://github.com/cloudfoundry/cf-java-client[CF-Java-Client] to listen to Cloudfoundry Firehose events

== Configuration and Deployment



* Set these environment variables:

```
FIREHOSE_HOST +
FIREHOSE_USER +
FIREHOSE_PASSWORD +
```
User and password must reference a cf user with the `doppler.firehose` scope in UAA.

* An app must be pushed to CF and bound to a metrics-forwarder service and publish metrics to the metrics-forwarder.  Spring Boot Apps with Boot Actuators enabled andusing the latest Java Build Pack will do this by default.  You can enhance those metrics using dropwizard metrics https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html#production-ready-dropwizard-metrics

* Start the application
[source]
----
./gradlew bootRun
----

== Discover Custom Metrics
* To start caching metric names for a specific app :
[source]
----
curl -X POST "http://localhost:8080/apps/{Application GUID}/metric_cache"
----

* To view cached metric names for a specific app :
[source]
----
curl "http://localhost:8080/apps/{Application GUID}/metric_cache/names"
----

* To stop caching metric names for a specific app (this clears the metric name cache):
[source]
----
curl -X DELETE "http://localhost:8080/apps/{Application GUID}/metric_cache"
----

== Collecting and Aggregating Metrics
* If everything is configured, you should can start collecting metric by requesting:
[source]
----
curl -X POST "http://localhost:8080/apps/{Application GUID}/metric_collection/{Metric Name}"
----

After appoximately 30 seconds you can see aggregated metrics by hitting the following metrics endpoints:

[source]
----
curl -X POST "http://localhost:8080/apps/{Application GUID}/metrics/{Metric Name}"
----

[source]
----
 curl  "http://localhost:8080/apps/{Application GUID}/last_metric/{Metric Name}"
----

You can append a query param to any of the metrics enpoints to get only the specific aggregation you are interested in:

Aggregation options are:

.Table Title
|===
|Aggregation Name

|average

|min

|max

|sum
|===

For example:

[source]
----
curl  "http://localhost:8080/apps/{Application GUID}/last_metric/{Metric Name}?aggregation=average"
----

* To Stop monitoring for a specific app metric:
[source]
----
curl -X DELETE "http://localhost:8080/apps/{Application GUID}/metric_settings/{Metric Name}"
----


== Docs
* To View API docs visit:
[source]
----
http://localhost:8080/swagger-ui.html
----
