cf:
  host: ${FIREHOSE_HOST}
  user: ${FIREHOSE_USER}
  password: ${FIREHOSE_PASSWORD}
  skipSslValidation: true

logging:
  level:
    root: INFO

spring:
  jpa:
    hibernate:
      ddl-auto: create

  profiles:
    active: ${ACTIVE_SPRING_PROFILE}

